name: Build base image

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

  push:
    branches: [ main ]
    paths:
      - 'requirements.txt'

env:
  IMAGE_NAME: jamminiz-base

jobs:
  build-base:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          DOCKER_REPO: docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          VERSION: ${{ github.sha }}
        run: |
          docker build -t $DOCKER_REPO:$VERSION -t $DOCKER_REPO:latest -f Dockerfile-base .
          docker push $DOCKER_REPO --all-tags